server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: health
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhkycs
#    url: jdbc:mysql://81.68.219.205:3306/zhkscs
    username: root
    password: Passw0rd
  mail:
    host: smtp.qq.com
    port: 587
    username: hydraone123@qq.com
    password: infdnbmzfdvdbcdj
#    username: m72875509qiaonuo@163.com
#    password: YSXJFNOIFXAIRUJT
    default-encoding: utf-8
    properties:
      mail:
        smtp:
#          auth: true
#          starttls:
#            enable: false
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false
  redis:
#    host: 192.168.117.130
    host: 81.68.219.205
    port: 6379
    password: Passw0rd
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

debug: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# mybatis-plus 二级缓存
    cache-enabled: false
#logging:
#  level:
#    cn.geny.ainone.account.mapper: debug
#    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug

#minIO 地址
minio:
#  endpoint: http://81.68.219.205:19000
  endpoint: http://192.168.117.130:19000
  accessKey: root
  secretKey: Passw0rd